In [12]:
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import joblib

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\fishb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\fishb\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\fishb\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\fishb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [13]:
# title=input("Give title of your issue : ")
# description=input("Describe your issue : ")
titles=["Road blocked by heavy vehicles",
       "Broken footpath tiles causing injuries near market",
       "Uncollected medical waste outside clinic",
       "Prepaid auto rickshaw booth non-functional at bus stand",
       "Overhead metro construction debris falling on road",
       "Acid water from factory draining into locality",
       "Planted saplings in ward dying due to no maintenance",
       "Just finished binge-watching a new web series",
       "Looking for a good caterer for office party",
       "My colony won the best decorated society award",
       "Tips for growing tomatoes in terrace garden",
       "Enjoying picnic with friends in Sidra.",
       "Overflowing public trash can",
       "Looking for movie recommendations",
       "Missing manhole cover on cycling path",
       "Earn money working from home","Streetlight flickering and buzzing loudly"]
descriptions=["Road is blocked by a heavy vehicle and vehicle is not starting thereby leading to taraffic jam near Chammb.",
              "Several footpath tiles outside the Narwal vegetable market have cracked and uplifted. An elderly woman tripped and fractured her wrist last Tuesday. The broken tiles have sharp edges and the municipality has not responded in 9 days.",
              "A private clinic on GT Road is placing biomedical waste — used gloves, syringes, and bandages — in regular municipal bins outside the building. The waste is mixed with household garbage and is a serious infection risk for sanitation workers.",
              "The government prepaid auto rickshaw booth at the central bus stand has been locked and unstaffed for over three weeks. Passengers, especially women and tourists, are being overcharged and harassed by private auto drivers with no official recourse.",
              "During night construction work on the metro rail project near Bathindi, loose debris including iron rods and concrete chunks fell onto the road below. No safety netting or barricading was in place. A parked vehicle was damaged and pedestrians narrowly escaped.",
              "A chemical manufacturing unit near Gangyal industrial area is discharging acidic effluent through a pipe that opens directly into the open drain running through the residential colony. The drain water has turned yellow, the smell is suffocating, and residents report skin irritation.",
              "Over 200 saplings planted by the municipality during the green drive last month in Hudco Colony are dying because no watering or follow-up care has been done since plantation day. More than half are already completely dried up and wasted.",
              "Stayed up until 3 AM finishing the new thriller web series everyone is talking about. The storyline had so many twists and the finale was completely unexpected. Already looking for a similar show to start tomorrow. Sleep can wait.",
              "Our office team of 60 people is planning an end-of-year party next Friday. Need recommendations for a good caterer who can handle both vegetarian and non-vegetarian starters and main course. Budget is approximately 500 rupees per head.",
              "Our housing society won the best Diwali decoration award at the city level competition this year. Every building and garden was lit up beautifully. The residents' committee worked for two weeks on the setup. Very proud of our community spirit.",
              "Started a small terrace kitchen garden last month and the tomato plants are struggling. The leaves are turning yellow despite regular watering. Not sure if it is a soil issue or too much direct sunlight. Looking for expert gardening advice.",
              "This is a beautiful spot with lush green fields and natural feel.",
              "The large green trash bin at the entrance of City Park has not been emptied in over a week. Bags are piled on the ground around it, and stray dogs are tearing them open.",
              "Can anyone suggest a good horror movie to watch tonight? I'm bored and have Netflix.",
              "The iron cover of a manhole on the dedicated cycling path near Riverside Apartments is completely gone. The hole is about 2 feet deep and could cause serious injury to cyclists, especially at night.",
              "Make $500 daily! No experience needed. Click the link in my bio to join our WhatsApp group. Limited slots available.",
              "The streetlight pole outside house number 45 on Maple Street has been flickering violently for three nights and makes a loud electrical buzzing sound. Children are scared to walk past, and it seems like it could catch fire."
             ]
input_text=[]
for i in range(0,len(titles)):
    input_text.append(titles[i]+" "+descriptions[i])

In [14]:
stop_words=stopwords.words('english')
lemmatizer=WordNetLemmatizer()

In [15]:
processed_texts = []
for text in input_text:
    text = text.lower()
    tokens = word_tokenize(text)
    filtered = []
    for w in tokens:
        if w.isalpha() and w not in stop_words:
            filtered.append(w)
    lemmas = []
    for w in filtered:
        lemmas.append(lemmatizer.lemmatize(w))
    sentence = ""
    for w in lemmas:
        sentence += " " + w
    processed_texts.append(sentence.strip())

In [16]:
svc_model = joblib.load("svc_model.pkl")
nb=joblib.load('nb_model.pkl')
tfidf = joblib.load("tfidf_vectorizer.pkl")
rfc=joblib.load('rfc_model.pkl')

In [17]:
X_new = tfidf.transform(processed_texts)

In [18]:
predictions = svc_model.predict(X_new)
print(predictions)

[1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 0 1]


In [19]:
predictions = nb.predict(X_new)
print(predictions)

[1 1 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1]


In [20]:
predictions = rfc.predict(X_new)
print(predictions)

[1 1 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1]
